apiVersion: v1
kind: Service
metadata:
  name: container-health
  namespace: container-health
spec:
  selector:
    app: container-health
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP