apiVersion: v1
kind: Service
metadata:
  name: container-health
  labels:
    app: container-health
spec:
  selector:
    app: container-health
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP