apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: container-health-stage

resources:
  - ../base

replacements:
  - source:
      kind: ConfigMap
      name: image-tag
      fieldPath: data.tag
    targets:
      - select:
          kind: Deployment
          name: container-health
        fieldPaths:
          - spec.template.spec.containers.[name=container-health].image
        options:
          delimiter: ":"
          index: 1
      
configMapGenerator:
  - name: image-tag
    files:
      - tag=image-tag.txt